services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      # - POSTGRES_DB=${DB_NAME}
      # - POSTGRES_USER=${DB_USERNAME}
      # - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    build: ./client
    container_name: ft_transcendence-nginx-1
    ports:
      - "443:443"
    volumes:
      - ./static:/usr/share/nginx/html/html
      - ./client/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/conf/ssl:/etc/nginx/ssl
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./client:/app
  #   env_file:
  #     - .env
