services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      # - POSTGRES_DB
      # - POSTGRES_USER
      # - POSTGRES_PASSWORD
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  nginx-server:
    build: ./client   # Path to the Dockerfile for Nginx
    image: nginx-server           # The image name for Nginx
    container_name: ft_transcendence-nginx-1  # Name of the container
    ports:
      - "443:443"                 # Expose port 443 (HTTPS)
    networks:
      - transcendence-network         # Connect to the existing network
    volumes:
      - ./client/static/html:/var/www/html  # Mount your local HTML directory for static files (replace this path as needed)
      - ./client/conf:/etc/nginx/conf.d # Mount your Nginx configuration directory
    restart: on-failure            # Restart container if it fails

networks:
  transcendence-network:
    driver: bridge
  
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./client:/app
  #   env_file:
  #     - .env
