services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENV_VAR_NAME=value  # Add your environment variables here

  client:
    build:
      context: ./client
    ports:
      # - "3000:3000"
      - "8000:80"
    volumes:
      - ./client:/app
    environment:
      - ENV_VAR_NAME=value  # Add your environment variables here
      
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     - ENV_VAR_NAME=value  # Add your environment variables here
